# Libraries for scientific research

In [1]:
import numpy

In [2]:
numpy.loadtxt(fname='data/inflammation-01.csv', delimeter=',')

TypeError: loadtxt() got an unexpected keyword argument 'delimeter'

In [3]:
numpy.loadtxt(fname='data/inflammation-01.csv', delimiter=',')

array([[0., 0., 1., ..., 3., 0., 0.],
       [0., 1., 2., ..., 1., 0., 1.],
       [0., 1., 1., ..., 2., 1., 1.],
       ...,
       [0., 1., 1., ..., 1., 1., 1.],
       [0., 0., 0., ..., 0., 2., 0.],
       [0., 0., 1., ..., 1., 1., 0.]])

In [4]:
arthritis = numpy.loadtxt(fname='data/inflammation-01.csv', delimiter=',')

In [5]:
print(arthritis)

[[0. 0. 1. ... 3. 0. 0.]
 [0. 1. 2. ... 1. 0. 1.]
 [0. 1. 1. ... 2. 1. 1.]
 ...
 [0. 1. 1. ... 1. 1. 1.]
 [0. 0. 0. ... 0. 2. 0.]
 [0. 0. 1. ... 1. 1. 0.]]


In [6]:
print(type(arthritis))

<class 'numpy.ndarray'>


## Attributes (adjetives)

In [8]:
print(arthritis.dtype)
print(arthritis.shape)

float64
(60, 40)


In [10]:
print("first value in arthritis:", arthritis[0, 0])

first value in arthritis: 0.0


In [11]:
print("middle value:", arthritis[30, 20])

middle value: 13.0


In [12]:
print(arthritis[0:4, 0:10])

[[0. 0. 1. 3. 1. 2. 4. 7. 8. 3.]
 [0. 1. 2. 1. 2. 1. 3. 2. 2. 6.]
 [0. 1. 1. 3. 3. 2. 6. 2. 5. 9.]
 [0. 0. 2. 0. 4. 2. 2. 1. 6. 7.]]


In [13]:
print(arthritis[5:10, 0:10])

[[0. 0. 1. 2. 2. 4. 2. 1. 6. 4.]
 [0. 0. 2. 2. 4. 2. 2. 5. 5. 8.]
 [0. 0. 1. 2. 3. 1. 2. 3. 5. 3.]
 [0. 0. 0. 3. 1. 5. 6. 5. 5. 8.]
 [0. 1. 1. 2. 1. 3. 5. 3. 5. 8.]]


In [14]:
corner = arthritis[:3, 36:]
print(corner)

[[2. 3. 0. 0.]
 [1. 1. 0. 1.]
 [2. 2. 1. 1.]]


## Exericise

In [16]:
"oxygen"[1:4]

'xyg'

## Operations

In [17]:
double_arthritis = arthritis * 2

In [18]:
print("original")
print(arthritis[:3, 36:])
print("double")
print(double_arthritis[:3, 36:])

original
[[2. 3. 0. 0.]
 [1. 1. 0. 1.]
 [2. 2. 1. 1.]]
double
[[4. 6. 0. 0.]
 [2. 2. 0. 2.]
 [4. 4. 2. 2.]]


In [19]:
triple_arthritis = double_arthritis + arthritis
print(triple_arthritis[:3, 36:])

[[6. 9. 0. 0.]
 [3. 3. 0. 3.]
 [6. 6. 3. 3.]]


# Methods (verbs)

In [20]:
print(arthritis.mean())

6.14875


In [21]:
print("maximum inflammation:", arthritis.max())
print("minimum inflammation:", arthritis.min())
print("standard deviation:", arthritis.std())

maximum inflammation: 20.0
minimum inflammation: 0.0
standard deviation: 4.613833197118566


In [22]:
arthritis.size

2400

In [23]:
patient_0 = arthritis[0, :]
print("maximum inflammation for patient 0:", patient_0.max())

maximum inflammation for patient 0: 18.0


In [24]:
print("maximum inflammation for pation 2:", arthritis[2, :].max())

maximum inflammation for pation 2: 19.0


In [25]:
print(arthritis.max(axis=1))

[18. 18. 19. 17. 17. 18. 17. 20. 17. 18. 18. 18. 17. 16. 17. 18. 19. 19.
 17. 19. 19. 16. 17. 15. 17. 17. 18. 17. 20. 17. 16. 19. 15. 15. 19. 17.
 16. 17. 19. 16. 18. 19. 16. 19. 18. 16. 19. 15. 16. 18. 14. 20. 17. 15.
 17. 16. 17. 19. 18. 18.]


In [26]:
print(arthritis.max(axis=0))

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19. 20. 19. 18. 17. 16. 15. 14. 13. 12. 11. 10.  9.  8.  7.  6.  5.
  4.  3.  2.  1.]


In [27]:
print(arthritis.max(axis=1).shape)
print(arthritis.max(axis=0).shape)

(60,)
(40,)


In [28]:
print("the average of the standard deviation for all the patienst")
print(arthritis.std(axis=1).mean())

the average of the standard deviation for all the patienst
4.579294680644961


In [29]:
numpy.mean(numpy.std(arthritis, axis=1))

4.579294680644961